<?php

declare(strict_types=1);

namespace Leobsst\LaravelCookieConsent\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

final class CheckGoogleAdsenseAvailability
{
    /**
     * Handle an incoming request.
     *
     * @param  Closure(Request): (Response)  $next
     */
    public function handle(Request $request, Closure $next): Response
    {
        if (
            config('cookie-consent.GOOGLE_ADSENSE_CLIENT_ID') === null
            || ! config('cookie-consent.ENABLE_AUTOGENERATED_ADS_FILE', true)
        ) {
            abort(404);
        }

        return $next($request);
    }
}
